### ISSUE TITLE
Inserting a value into a different tier doesn't delete from the old tier

### ISSUE THREAD

**Issue by rkuris** [aeromilai/tiered-cache#6]
To reproduce, create two tiers, one of size (0, 64) and another (65, 1024). Then, insert the key twice, once into the first tier and then into the second tier with a larger value (same key). Fetching then results in the wrong value from the original tier.

Sample code:

```
        let key: Vec<u8> = b"example".to_vec();

        cache.put(key.clone(), vec![0u8; 1]);
        cache.put(key.clone(), vec![0u8; 65]);

        let retrieved = cache.get(&key).unwrap();
        assert_eq!(retrieved.len(), 65);
```

**Comment by kolinfluence** [comment]
fixed
